### PR TITLE
as: Minor refactorings

### PR DESCRIPTION
**Pull request by MaxGraey**

### CODE REVIEW

**Comment by radu-matei** [comment]
Hi, @MaxGraey!
Currently, the runtime expects an allocation function called `alloc` to be exported by the module.

https://github.com/deislabs/wasi-experimental-http/blob/fe268e5fe5e180e06fbe5f826e4f335dc1ea5b21/crates/wasi-experimental-http-wasmtime/src/lib.rs#L11

This is not ideal, and obviously a workaround, so I'm open to suggestions - essentially, the runtime expects to be able to allocate buffer arrays into the module's linear memory, so if we could reuse the AssemblyScript functions that do that, it would be great.

**Comment by radu-matei** [comment]
Also see #32.

Basically, we should find a consistent way for the runtime to allocate memory into the guests' linear memory regardless of the implementation, and I'm open to suggestions.

**Comment by MaxGraey** [comment]
I see, thanks. So instead exporting `alloc` you could reuse standard `__alloc` (unmapaged) or `__new` (managed) which exposed by `--exportRuntime` flag.

__alloc: https://www.assemblyscript.org/garbage-collection.html#custom-runtime
__new: https://www.assemblyscript.org/garbage-collection.html#runtime-interface

it uses as `__alloc(len, 0)` (this required `__free` for avoid mem leak) or `__new(len, 0)` (this managed and will be collected by incremental GC)

**Review by radu-matei — APPROVED** [review]
Thank you so much for your contribution!
Let's continue the conversation about the `alloc` function in #32 and not keep this PR from getting merged.

LGTM

**Pull request merged**
