### PR TITLE
chore: update to wasmtime 0.35

### PR DESCRIPTION
**Pull request by Mossaka**
Signed-off-by: Jiaxiao Zhou <jiazho@microsoft.com>

### CODE REVIEW

**Comment by radu-matei** [comment]
Does this supersede #90?

**Comment by Mossaka** [comment]
> Does this supersede #90?

yes we can close #90

**Comment by Mossaka** [comment]
ready to merge? @radu-matei

**Comment by derekbar90** [comment]
Looks like things are passing, is there a reason this wasn't merged?

**Review by radu-matei — APPROVED** [review]

**Pull request merged**
